name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bradennapier/eslint-plus-action@v3.4.2

      - uses: Cyb3r-Jak3/html5validator-action@v7.1.0
        with:
          root: /
          css: true
          format: json
