name: Update Get-My-Commits Fetch Date

on:
  schedule:
    - cron: "0 0 1 1 *"
    - cron: "0 0 20 5 *"
    - cron: "0 0 20 8 *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Get Today
      - run: |
          today=$(date +'%Y-%m-%dT00:00:00Z')
          echo $today
      
      - name: Replace Date
      - run: sed -i "s|FETCHSINCE \= \".*\"|FETCHSINCE \= \"$today\"|g" ./get-my-commits/index.js
